### ISSUE TITLE
Add commas to the chat reminder

### ISSUE THREAD

**Issue by DustyFan** [Bash-09/tf2-bot-kicker-gui#22]
![asahgrtk](https://user-images.githubusercontent.com/87148159/175873128-7b42c59b-d9a4-4da0-bbce-f394eaf2882c.jpg)
There were four bots in the match with the names: close, for, people, pray.
Due to the fact that the program does not put a comma, you may get a sentence or mush of words.

![rtjdrtjdrt](https://user-images.githubusercontent.com/87148159/175879928-72882e00-f75d-4841-824a-87b5c0c01e50.jpg)
Even if the bots have the same name, without the comma it would still look like a mush of names.

**Comment by Bash-09** [comment]
Hi, the program has since changed a fair bit including all kinds of chat messaged being reworked. If you download and use the latest release regular chat reminders have been removed (maybe temporarily, if anybody wants them back) and the messages for bots and cheaters connecting to the server do not suffer from this issue anymore.
