### ISSUE TITLE
Crash Upon Start (Wrong glibc Version)

### ISSUE THREAD

**Issue by SylvKT** [Bash-09/tf2-bot-kicker-gui#28]
Upon starting the latest version of `tf2-bot-kicker-gui`, the program instantly crashes.
For context, I am using Ubuntu 20.04
# Log
```
./tf2-bot-kicker-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tf2-bot-kicker-gui)
./tf2-bot-kicker-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tf2-bot-kicker-gui)
```

**Comment by SylvKT** [comment]
Upon first glance, this seems to be an issue with one of the dependencies. I'll take a closer look at this.

**Comment by SylvKT** [comment]
Also, why did you put the binary in the source?

**Comment by Bash-09** [comment]
> Upon starting the latest version of `tf2-bot-kicker-gui`, the program instantly crashes. For context, I am using Ubuntu 20.04
> # Log
> 
> ```
> ./tf2-bot-kicker-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tf2-bot-kicker-gui)
> ./tf2-bot-kicker-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tf2-bot-kicker-gui)
> ```

Apologies, this must be because I compiled it on a machine with a relatively recent version of `glibc`. You can overcome this yourself if you wish to compile the program from source and run it yourself (should hopefully be as simple as `cargo run --release`, but may need a few libraries installed), otherwise I am working on a new release which I can push forward which I will compile with a lower `glibc` requirement. 

> Also, why did you put the binary in the source? If you just want an easy way to package the binary for distribution (I see the `cfg` folder), you can use a `build.rs` script for that.

This was purely a convenience for myself and should probably be removed tbh, will do that at some point. The `cfg` folder is to store the runtime data such as the saved player list, regex matching rules and user settings (although I have that one `.gitignore`d).

**Comment by Bash-09** [comment]
Just to check, what version of `glibc` are you running? You should be able to check with `ldd --version`

**Comment by SylvKT** [comment]
2.31

**Comment by Bash-09** [comment]
I just added a new release which should hopefully work for you
